import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../src/components/CartContext";
import CartButton from "../src/components/CartButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Electronics Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <header className="bg-white border-b">
            <div className="max-w-5xl mx-auto p-4 flex items-center justify-between">
              <a href="/" className="font-bold text-black"> 
                My Shop 
              </a>
              <nav className="flex items-center gap-4">
                <a href="/" className="text-sm font-medium text-zinc-700 hover:text-indigo-600">
                  Home
                </a>
                <a href="/favs" className="text-sm font-medium text-zinc-700 hover:text-indigo-600">
                  Favorites
                </a>
                <div className="ml-4">
                  <CartButton />
                </div>
              </nav>
            </div>
          </header>
          <main className="flex-1">{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
